# Generated by Django 5.1 on 2024-08-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.URLField(null=True)),
                ('release_date', models.DateField(default='0000-00-00')),
                ('lte_exists', models.BooleanField(null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
