name: Multiple Homeworks Publishing

on:
  push:
    branches: [ "main" ]
    #paths: 
    #  - '9-JavaScript-browser'
      
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        include:
          - page-path: '9-JavaScript-browser/2-DOM/hit-game/'
            page-url: 'hit-game'            

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        echo ${{ matrix.page-path }}dist/
        echo ${{ steps.deployment.outputs.page_url }}${{ matrix.page-url }}
        cd ${{ matrix.page-path }}        
        npm install webpack webpack-cli html-webpack-plugin
        npx webpack
        mkdir -p /home/runner/work/_temp/dist/${{ matrix.page-url }}
        cp -r dist/* /home/runner/work/_temp/dist/${{ matrix.page-url }}

  upload:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Upload Pages
      uses: actions/upload-pages-artifact@v3
      id: deployment
      with:
        path: /home/runner/work/_temp/dist
          
  deploy:
    needs: [build, upload]
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deployment
