name: Multiple Homeworks Publishing

on:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/**'
      - '9-JavaScript-browser/**'

env:
  HOME_URL: 'https://danbzay.github.io/netology/'
      
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - page-path: '9-JavaScript-browser/2-DOM/hit-game/'
            page-name: 'hit-game'  
            node-version: 22.x
          - page-path: '9-JavaScript-browser/2-DOM/loading-sorting/'
            page-name: 'loading-sorting'
            node-version: 22.x

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Create home page
      run: 

    - name: Save old version of page if actual
      id: old_page
      run: |  
        regex_page_path=$(echo "${{ matrix.page-path }}" | sed 's/[.\/]/\\&/g')
        git show --dirstat HEAD        
        git show --dirstat HEAD | grep ($regex_page_path|github) || 
          wget -r -np ${{ HOME_URL }}${{ matrix.page-name }} &&
          echo 'saved=true' >> $GITHUB_OUTPUT

    - name: Check page existance if not modified
      id: check_page_exist
      if: ${{steps.old_page.outputs.saved != true }}
      run: | 
        wget -r -np ${{ HOME_URL }}${{ matrix.page-name }} ||           
          echo 'exist=false' >> $GITHUB_OUTPUT

    - name: Use Node.js ${{ matrix.node-version }}
      if: ${{steps.old_page.outputs.saved != true }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
   
    - name: Build
      if: ${{steps.old_page.outputs.saved != true }}
      run: |
        cd ${{ matrix.page-path }}        
        npm install
        npx eslint
        npx webpack

    - name: Upload Page Artifact
      if: ${{steps.old_page.outputs.saved != true }}
      uses: actions/upload-artifact@v4
      with:
        path: ${{ matrix.page-path }}dist 
        name: ${{ matrix.page-name }}
        retention-days: 30
        overwrite: true
          
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    
    steps:
    - name: Download and Combine Pages
      uses: actions/download-artifact@v5
        
    - name: Display structure of downloaded files
      run: ls -R

    - name: Upload Combined Pages Artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ github.workspace }}      
        name: combined
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deployment
      with:
        artifact_name: combined
